### ISSUE TITLE
Create an 'admin' user that has the ability to use sudo

### ISSUE THREAD

**Issue by tom-butler** [opendatacube/jupyterhub#18]
will enable admin users to perform interactive development, without directly starting the container as root user.

**Comment by Kirill888** [comment]
Rather than creating a separate admin user it's best to [optionally] give `sudo` permission to the default `jovyan` user. This does require having separate images/tags for `sudo/non-sudo` use-cases, but on a plus side there is no problem with file permissions when user sometimes uses admin option on sandbox and non-admin option other times.

I done that in #24, `sudo` enabled image is pushed to `{tag}_sudo` and is only few layers different from `non-sudo` image.
